name = "BinaryParsingTools"
uuid = "6663bfc4-f836-4634-93ec-aee42a53a86a"
authors = ["CÃ©dric BELMANT"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
